<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>wuwa2blender</AssemblyName>
    <RootNamespace>Wuwa.Cli</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Wuwa.Core/Wuwa.Core.csproj" />
    <ProjectReference Include="../Wuwa.Extractor/Wuwa.Extractor.csproj" />
    <ProjectReference Include="../Wuwa.Export/Wuwa.Export.csproj" />
  </ItemGroup>
</Project>
